### ISSUE TITLE
Sync workflow that will build Docker image on release to auto-releasing repos

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/workflows#45]
- Should incoporate decision of https://github.com/neurobagel/recipes/issues/9
- Maybe we can use something like this https://github.com/BetaHuhn/repo-file-sync-action?tab=readme-ov-file#using-templates to replace the repo name with a variable for different Docker images

# TODO:
- [x] add `build_docker_on_release.yml`
- [x] make sure any newly built docker image with a SEMVER has the `latest` tag (meaning, "latest stable") and not `stable`
- [ ] delete current `stable` tag on the releasing repos? (maybe after next `latest` release?)
