### ISSUE TITLE
Add nightly docker build to synced workflows

### ISSUE THREAD

**Issue by surchs** [neurobagel/workflows#92]
The following repos have the docker nightly build workflow (with different names):

- [ ] [query-tool](https://github.com/neurobagel/query-tool/blob/f43b074ec772fcd53c98d01c5a54db056f0f0fc7/.github/workflows/build_docker_nightly.yaml)
- [ ] [bagel-cli](https://github.com/neurobagel/bagel-cli/blob/44e0a986f0347f223ba08e1c21cf3ade91fa3184/.github/workflows/cd.yml)
- [ ] [api](https://github.com/neurobagel/api/blob/bc6bb9f4d180a3d19d26333b0032ad35f37f4a26/.github/workflows/build_docker.yaml)
- [ ] [federation-api](https://github.com/neurobagel/federation-api/blob/df85e481a4079ad869ba4c9bdf45121ace26da96/.github/workflows/build_docker.yaml)

All of these workflows should be replaced by a single synced workflow. 
This might require either making the docker image name match the github repo name (or vice versa), 
or setting a repository env variable to configure the base name of the Docker image we are building

## TODO
- [x] we will have to delete the possibly differently named nightly workflows in the repos first
- [x] make a new template nightly build workflow
- [ ] sync it to the repos
- [ ] confirm that the workflow works

**Comment by alyssadai** [comment]
note: this would also be affected by
- https://github.com/neurobagel/workflows/issues/97
